### ISSUE TITLE
User didn´t get moved

### ISSUE THREAD

**Issue by Asrothear** [ripkens/SaltyChat-AltV#2]
We have the problem that the player diddn´t get moved into the voice channel, the two events
alt.emit("SaltyChat_OnConnected"); and alt.emit("PlayerLoggedIn", client); where called but nothing happend.

**Comment by Fynnoverse** [comment]
to clarify things:

i added client side an eventlistener:

```
alt.onServer('SC_OnConnected', SC_OnConnected)

function SC_OnConnected(){
    alt.log("SC_OnConnected")
    alt.emit("SaltyChat_OnConnected");
}
```

Server side is a Char-Selction inside this there is the following:
```
    alt.setTimeout(() => {
        player.emitMeta('loggedin', true)
        alt.emit("PlayerLoggedIn", player);
        alt.log('emit("PlayerLoggedIn")')
        alt.emitClient(player, "SaltyChat_OnConnected")
        alt.emitClient(player, "SC_OnConnected")
        alt.emitClient(player, "SaltyChat_UpdateRadioTowers", JSON.stringify(RadioTowers))
        if(player.data.dead) {
            alt.emitClient(null, 'SaltyChat_PlayerDied', player)
        }
        syncAllDoors(player);
        player.syncInventory(true);
    }, 1000)
```

All logs are appearing in the Server and Client Console...

**Comment by ripkens** [comment]
`alt.onServer("SaltyChat_OnConnected", this.OnPluginConnected);`

Its an Event that has to come from Server not client.
If you emit it from client you have to change it to:

`alt.on("SaltyChat_OnConnected", this.OnPluginConnected);`

in index.mjs
