### ISSUE TITLE
A Question about Radiochannels

### ISSUE THREAD

**Issue by leonkappes** [ripkens/SaltyChat-AltV#3]
So I've looked into your code and started wondering, how do you handle the Radio? From what it seems you just don't?!?
And I don't understand why you add every channel into an Array, how do you decide which channel should be used.

Wanted to contribute that functionality but can't get the grasp about what you're trying to achieve.

**Comment by Fynnoverse** [comment]
Yes he dont handle this ^^ I re-wrote this so this works for us

**Comment by leonkappes** [comment]
Yes was thinking of rewriting it and making a Pull-Request, but it doesn't seem to be maintained.
